### ISSUE TITLE
Using STARTTLS breaks LDAP authentication

### ISSUE THREAD

**Issue by oschlueter** [neo4j/neo4j#12047]
### Abstract

I discovered that when I configure the LDAP Auth Provider to use STARTTLS authentication is broken, i.e. I can log into the Neo4j instance with any existing user account using arbitrary passwords. 
Unencrypted LDAP connections (without STARTTLS) and LDAPS connections are not affected.

- Neo4j version: 3.4.4-enterprise (also reproduced with 3.4.7-enterprise)
- Operating system: Alpine (via Docker)
- API/Driver: ?

### Steps to reproduce
1. Create `docker-compose.yml`:
```yaml
version: '3.4'

services:
  openldap:
    image: osixia/openldap:1.2.2
    ports:
      - 1389:389
      - 1636:636
    environment:
      - LDAP_BASE_DN=
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=bind
      - LDAP_READONLY_USER_PASSWORD=bind
      - LDAP_TLS_VERIFY_CLIENT=try
      - LDAP_TLS_CRT_FILENAME=openldap.crt
      - LDAP_TLS_KEY_FILENAME=openldap.key
      - LDAP_TLS_CA_CRT_FILENAME=ca.crt
    volumes:
      - $PWD/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/bootstrap.ldif
      - $PWD/certs:/container/service/slapd/assets/certs
    command: --copy-service

  neo4j:
    image: neo4j:3.4.4-enterprise
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - $PWD/neo4j.conf:/conf/neo4j.conf
      - $PWD/logs:/logs
      - $PWD/certs/truststore.jks:/etc/neo4j/truststore.jks
```
2. Pull Docker images: `docker-compose pull`
3. Create `bootstrap.ldif`:
```text
dn: ou=groups,dc=example,dc=org
objectClass: organizationalUnit
ou: groups
description: generic groups branch

dn: ou=people,dc=example,dc=org
objectClass: organizationalUnit
ou: people
description: generic people branch

dn: uid=alice,ou=people,dc=example,dc=org
uid: alice
cn: alice
sn: smith
objectClass: inetOrgPerson
userPassword: alice

dn: cn=everyone,ou=groups,dc=example,dc=org
objectClass: groupOfUniqueNames
cn: everyone
description: Contains every account 
uniqueMember: uid=alice,ou=people,dc=example,dc=org
```
4. Create certificates and truststore
```commandline
mkdir certs && cd certs && \
openssl genrsa -out ca.key 1024 && \
openssl req -new -x509 -key ca.key -out ca.crt -nodes -subj '/CN=CA' && \
openssl genrsa -out openldap.key 1024 && \
openssl req -new -key openldap.key -out openldap.csr -subj '/CN=openldap' && \
openssl x509 -req -in openldap.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out openldap.crt && \
openssl dhparam -out dhparam.pem 256 && \
keytool -keystore truststore.jks -alias CARoot -import -file ca.crt -storepass truststore -noprompt && \
cd ..
```
5. Create `neo4j.conf`:
```text
dbms.connector.https.enabled=false

dbms.security.auth_provider=ldap
dbms.security.auth_cache_ttl=0

dbms.security.ldap.host=ldap://openldap
dbms.security.ldap.use_starttls=true
dbms.security.ldap.authentication.user_dn_template=cn={0},ou=people,dc=example,dc=org

dbms.security.ldap.authorization.use_system_account=true
dbms.security.ldap.authorization.system_username=cn=bind,dc=example,dc=org
dbms.security.ldap.authorization.system_password=bind

dbms.security.ldap.authorization.user_search_base=ou=people,dc=example,dc=org
dbms.security.ldap.authorization.user_search_filter=(&(objectClass=*)(uid={0}))
dbms.security.ldap.authorization.group_membership_attributes=memberOf

dbms.security.ldap.authorization.group_to_role_mapping=\
          "cn=everyone,ou=groups,dc=example,dc=org"      = reader;    \
          "cn=everyone,ou=groups,dc=example,dc=org"      = publisher;    \
          "cn=everyone,ou=groups,dc=example,dc=org"  = architect;    \
          "cn=everyone,ou=groups,dc=example,dc=org"   = admin;

dbms.jvm.additional=-Djavax.net.ssl.trustStore=/etc/neo4j/truststore.jks
dbms.jvm.additional=-Djavax.net.ssl.trustStorePassword=truststore
```
6. Create `logs` directory: `mkdir logs`
7. `docker-compose up`
8. Verify STARTTLS works and account alice exists:
```
LDAPTLS_REQCERT=never ldapwhoami -D uid=alice,ou=people,dc=example,dc=org -H ldap://localhost:1389 -w alice -ZZ
```
Corresponding LDAP log:
```
openldap_1  | 5bb760bb conn=1000 fd=12 ACCEPT from IP=192.168.32.1:51174 (IP=0.0.0.0:389)
openldap_1  | 5bb760bb conn=1000 op=0 EXT oid=1.3.6.1.4.1.1466.20037
openldap_1  | 5bb760bb conn=1000 op=0 STARTTLS
openldap_1  | 5bb760bb conn=1000 op=0 RESULT oid= err=0 text=
openldap_1  | 5bb760bb conn=1000 fd=12 TLS established tls_ssf=256 ssf=256
openldap_1  | 5bb760bb conn=1000 op=1 BIND dn="uid=alice,ou=people,dc=example,dc=org" method=128
openldap_1  | 5bb760bb conn=1000 op=1 BIND dn="uid=alice,ou=people,dc=example,dc=org" mech=SIMPLE ssf=0
openldap_1  | 5bb760bb conn=1000 op=1 RESULT tag=97 err=0 text=
openldap_1  | 5bb760bb conn=1000 op=2 EXT oid=1.3.6.1.4.1.4203.1.11.3
openldap_1  | 5bb760bb conn=1000 op=2 WHOAMI
openldap_1  | 5bb760bb conn=1000 op=2 RESULT oid= err=0 text=
openldap_1  | 5bb760bb conn=1000 op=3 UNBIND
openldap_1  | 5bb760bb conn=1000 fd=12 closed
```
9. Open Neo4J in your browser at `http://localhost:7474` and login using the account `alice` and the password `bob`

### Expected behavior
Login fails with error message ` Neo.ClientError.Security.Unauthorized: The client is unauthorized due to authentication failure.`

### Actual behavior
Login succeeds.
