### ISSUE TITLE
NEO4J in a docker does not use TLS via bolt

### ISSUE THREAD

**Issue by UnreleasedCode** [neo4j/neo4j#12351]
### Steps to reproduce
1. Run a NEO4J with docker-compose (NOT local)
2. Set up SSL with Certbot
3. Install NEO4J and connect to a remote graph using "Encrypted Connection"

### Expected behavior
Encrypted Connection should be established

### Actual behavior
`Unable to establish remote connection: Database is unreachable with specified configuration.` and
`Unable to establish remote connection: ServiceUnavailable`

### More Info
I am a student and this is one of my projects. 
Currently I want to use the ETL-Tool to get the data from a SQL-Database into NEO4J.
It is sensitive data and so it is very important to use an encrypted connection.

I am using:
Neo4j Server version: 3.5.12 (community)
on an Ubuntu 19.04 disco

NEO4J runs inside a docker container.
### Docker compose file
```
version: '3'

services:
  neo4j:
    restart: always
    image: neo4j:latest
    network_mode: "bridge"
    ports:
      - "7687:7687"
      - "7473:7473"
    environment:
      - NEO4J_dbms_memory_heap_initial__size=2048m
      - NEO4J_dbms_memory_heap_max__size=2048m
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - ./plugins:/plugins
      - ./data:/data
      - ./import:/import
      - ./ssl:/ssl
      - ./conf/:/conf
```

The ssl certificate works great when browse via URL to the database, however I got an error by connecting via the NEO4J Desktop application (with tick "Encrypted Connection").
I am only able to connect via the ETL-Tool by unticking the encrypted connection, so I looked into the docu and found this configuration:
      `- NEO4J_dbms_connectors_bolt_tls__level=REQUIRED`

But with this parameter set, I do not got any connection to the graph via NEO4J Desktop and still got the same errors..
The logs inside the container does not support helpful information.
