### ISSUE TITLE
Neo4j import folder not linked in Docker volume

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [neo4j/neo4j#12710]
- Neo4j version: latest from Docker hub
- Operating system: Ubuntu 20.04 with Docker/Docker-compose
- 
## Bug report
If I mount a volume to `/import` the data doesn't appear in the container and if I write in the `/import` folder in the container nothing appears in the host folder.

This is my docker-compose file
```
version: "3"
services:
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $VOLUMES/neo4j/data:/data
      - $VOLUMES/neo4j/plugins:/plugins
      - $VOLUMES/neo4j/logs:/logs
      - $VOLUMES/neo4j/import:/import

    environment:
      - NEO4J_AUTH=neo4j/test
    network_mode: host

```
### Steps to reproduce
1. Pull the image: `docker pull neo4j:latest`
2. Create the previous docker-compose file
3. Run it
4. Attach a shell to the container, `cd /import` and `touch foo.txt`
5. `foo.txt` is not in the volume `$VOLUMES/neo4j/import`

### Expected behavior
The volume should the correct linked to `/import`
### Actual behavior
The volume is not linked to `/import`

**Comment by paldeep-singh** [comment]
Were you able to fix this? I am currently having the same issue.

**Comment by paldeep-singh** [comment]
In case anyone is looking for an answer, I was able to mount the import folder by changing `/import` to `/var/lib/neo4j/import` as suggested in [this](https://stackoverflow.com/questions/68850174/mounting-directory-in-neo4j-docker-container-is-resulting-in-empty-directory-on/68850338#68850338?newreg=efc991ce228f4af1a418019894c6c7d0) post on stackoverflow.

For the above example, the line should be:
```
- $VOLUMES/neo4j/import:/var/lib/neo4j/import 
```

**Comment by ThomasThelen** [comment]
This is how I mount local data to the neo4j container, without issue

```
services:
  neo4j:
    image: neo4j:5.11.0-community-bullseye
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4j1234
    volumes:
      - some/local.dir/with/import/data:/var/lib/neo4j/import
```
