### ISSUE TITLE
Cannot set up causal cluster using docker-compose when services have underscores in their name

### ISSUE THREAD

**Issue by topher235** [neo4j/neo4j#12729]
I discovered that when I define a Neo4j Core service name in docker-compose with an underscore, the Cores are not able to find each other. For example, when I find and replace all `neo4j_core01` -> `core1`, `neo4j_core02` -> `neo4j_core2`, and `neo4j_core03` -> `core3`, the services are able to find each other and the cluster starts.

I tried letting it run for ~5 minutes, but the only log I saw was `Database 'system' is waiting for a total of 3 core members...`. I also tried a newer Neo4j version, but no change.

**Neo4j Version:** 4.0.6-enterprise
**Operating System:** Ubuntu 15.10
**API:** Docker

### Steps to reproduce
1. Copy the Dockerfile contents into a local Dockerfile
2. Copy the docker-compose contents into a local docker-compose.yml file
3. May need to change the build context in the docker-compose file
4. Build the dockerfile -- `docker-compose build`
5. Start the Neo4j cluster -- `docker-compose up`

### Expected behavior
The Neo4j causal cluster should start and be available at localhost:7474/browser

### Actual behavior
The Neo4j causal cluster does not start and only logs `Database 'system' is waiting for a total of 3 core members...`.

### Dockerfile
```
FROM neo4j:4.0.6-enterprise

ENV NEO4J_AUTH=neo4j/letmein

ENV APOC_VERSION 4.0.0.18
ENV APOC_URI https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/${APOC_VERSION}/apoc-${APOC_VERSION}-all.jar
RUN wget -P /var/lib/neo4j/plugins ${APOC_URI}

EXPOSE 7474 7473 7687

CMD ["neo4j"]
```

### Docker-compose
```
version: '3'

services:

  neo4j_core01:
    build: ./neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_AUTH=none
      - NEO4J_apoc_trigger_enabled=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_causal__clustering_initial__discovery__members=neo4j_core01:5000,neo4j_core02:5000,neo4j_core03:5000
      - NEO4J_dbms_mode=CORE
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
      - NEO4J_causal__clustering_discovery__advertised__address=neo4j_core01:5000
      - NEO4J_causal__clustering_transaction__advertised__address=neo4j_core01:6000
      - NEO4J_causal__clustering_raft__advertised__address=neo4j_core01:7000
    volumes:
      - ./var/neo4j/data:/data
      - ./var/neo4j/logs:/logs
    networks:
      - lan

  neo4j_core02:
    build: ./neo4j
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_AUTH=none
      - NEO4J_apoc_trigger_enabled=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_causal__clustering_initial__discovery__members=neo4j_core01:5000,neo4j_core02:5000,neo4j_core03:5000
      - NEO4J_dbms_mode=CORE
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
      - NEO4J_causal__clustering_discovery__advertised__address=neo4j_core02:5000
      - NEO4J_causal__clustering_transaction__advertised__address=neo4j_core02:6000
      - NEO4J_causal__clustering_raft__advertised__address=neo4j_core02:7000
    networks:
      - lan

  neo4j_core03:
    build: ./neo4j
    ports:
      - "7476:7474"
      - "7689:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_AUTH=none
      - NEO4J_apoc_trigger_enabled=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_causal__clustering_initial__discovery__members=neo4j_core01:5000,neo4j_core02:5000,neo4j_core03:5000
      - NEO4J_dbms_mode=CORE
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
      - NEO4J_causal__clustering_discovery__advertised__address=neo4j_core03:5000
      - NEO4J_causal__clustering_transaction__advertised__address=neo4j_core03:6000
      - NEO4J_causal__clustering_raft__advertised__address=neo4j_core03:7000
    networks:
      - lan
networks:
  lan:
    driver: bridge
```
