### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by soda92** [neo4j/neo4j#12875]
Windows: https://github.com/soda92/neo4j/runs/6171632857?check_suite_focus=true
Ubuntu: https://github.com/soda92/neo4j/runs/6171632771?check_suite_focus=true

**Comment by klaren** [comment]
The windows build runs with the wrong version of Java, most likely 1.8.

I would suggest you use this instead:
```yaml
steps:
  - uses: actions/checkout@v3
  - name: Set up JDK 11
    uses: actions/setup-java@v3
    with:
      java-version: '11'
      distribution: 'adopt'
      cache: maven
  - name: Build with Maven
    run: mvn ...
```

The ubuntu one fails on licensing checks, it might be some error due to caching, I'll investigate further. In the meantime you can just pass `-Dlicensing.skip` to maven and it will completely skip this check.
