### ISSUE TITLE
[Monitoring][Prometheus] Use database name as metric additional label

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#13092]
Version: 5.6.0-enterprise
OS: any

Prometheus metrics exposed have the following metric name 

```
neo4j_database_<db_name>_ids_in_use_node
```

which is working fine, however not very convenient because we have to rewrite them for building dynamic dashboards and have the database name as a proper metric label, here a metric rewrite example with prometheus : 

```
metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(neo4j_database)_([a-zA-z0-9_]+)_((ids|check|cypher|db|pool|store|transaction)_[a-z_]+)'
        replacement: '${2}'
        target_label: database
        action: replace
      - source_labels: [__name__]
        regex: '(neo4j_database)_([a-zA-z0-9_]+)_((ids|check|cypher|db|pool|store|transaction)_[a-z_]+)'
        replacement: 'neo4j_database_$3'
        target_label: __name__
        action: replace
```

It would be great if we can have generic metric names with the database name as a label ( the output of the rewrite above but natively exposed by the neo4j server)

```
neo4j_database_ids_in_use_node({target=neo4j, database=neo4j})
```
