### ISSUE TITLE
`apoc.coll.indexOf` unexpectedly treats collections differently than the "same" hardcoded list

### ISSUE THREAD

**Issue by NilsMoller** [neo4j/neo4j#13175]
I discovered that when using `apoc.coll.indexOf` on objects which have an array as a property, it does not get the index correctly. It does work correctly when the collection passed to `indexOf` is the "same" hardcoded list. This is shown very well in the accepted answer to [my StackOverflow question](https://stackoverflow.com/questions/76102000/how-can-i-find-the-index-of-an-object-which-contains-an-array-as-a-property-from). The answer also contains a workaround for this issue for now.

**Neo4j Version:** 5.7.0
**Operating System:** Windows 10
**API:** Docker, APOC

### Steps to reproduce
1. Create a Neo4j Docker image using the following `docker-compose` service:
```yaml
bug-report-neo4j:
  image: neo4j:5.7.0
  container_name: bug-report-neo4j
  environment:
    NEO4J_dbms_logs_debug_level: DEBUG
    NEO4J_AUTH: neo4j/securepassword
    NEO4J_dbms_directories_plugins: "/var/lib/neo4j/labs"
    NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
    NEO4J_dbms_security_procedures_allowlist: "gds.*,apoc.*"
    NEO4J_apoc_export_file_enabled: "true"
    NEO4J_apoc_import_file_enabled: "true"
    NEO4J_apoc_import_file_use__neo4j__config: "true"
  ports:
    - "7474:7474"
    - "7687:7687"
```
3. Create two nodes which contain an array property:
```cypher
CREATE (test:Test { someArray: [true, false, true] })
CREATE (test2:Test { someArray: [] })
``` 
4. Match all on label `Test`, collect the results, and use `apoc.coll.indexOf` to find the index of an item:
```cypher
MATCH (n:Test)

WITH COLLECT({
    someArray: n.someArray
}) as collection

RETURN apoc.coll.indexOf(collection, { someArray: [] })
```

### Expected behavior
The query in step 4 returns either `0` or `1` (depending on the order of the list).

### Actual behavior
The query in step 4 returns `-1`. 
It does work correctly using this query:
```cypher
MATCH (n:Test)

WITH COLLECT({
    someArray: n.someArray
}) as collection

RETURN apoc.coll.indexOf([{someArray: [true, false, true]}, {someArray: []}], {someArray: []})
```
