### ISSUE TITLE
Bolt accepts unencrypted connection

### ISSUE THREAD

**Issue by Ekkerh** [neo4j/neo4j#13369]
## Case
I am trying to confirm that the neo4j database instance is correctly configured to reject bolt connections that are not encrypted. I have configured `server.bolt.tls_level=REQUIRED`, which should make the database reject unencrypted connections

- Neo4j version: 5.11.0
- Operating system: Ubuntu 22.04

## Steps to reproduce
- Create a self signed certificate: `openssl req -x509 -nodes -newkey rsa:2048 -keyout private.key -out public.crt -days 365` and insert private.key in ./ssl/bolt/ and insert public.crt in ./ssl/bolt/ and in ./ssl/bolt/trusted/ into the attachment that I provide.
- Spin up the docker-compose file that is provided as an attachment: `docker compose -f docker-compose.yaml up`
- Connect to database using neo4j Desktop: url: neo4j://localhost:20001, username: neo4j, password: testtest and do not check "Use encrypted connection"

## Expected behavior
The database should reject the unencrypted connection

## Actual behavior
The database accepts the unencrypted connections as well as encrypted connections. When I set `server.bolt.tls_level=DISABLED`, however, the encrypted connections are rejected, which indicates that I am configuring the correct setting.

[neo4j_hosting.zip](https://github.com/neo4j/neo4j/files/13714467/neo4j_hosting.zip)

**Comment by robsdedude** [comment]
Thanks for reaching out.

Do you mind posting the docker compose file as

```
code snippet
```
I'm not fond of downloading a zip.

If you're worried about size, you can use
````
<details>
<summary>Docker compose file</summary>

```yaml
# ...
```

</details>
````
Like so:
<details>
<summary>Docker compose file</summary>

```yaml
# ...
```

</details>

**Comment by Ekkerh** [comment]
Hi,

Will do. So, the file structure inside the .zip-file is the following:
```
ssl
 └-bolt
    |-trusted
    └-revoked
conf
  |-neo4j.conf
  └-apoc.conf
docker-compose.yaml
```

The content of the files are as follows:

neo4j.conf:
```
# bolt ssl conf
dbms.ssl.policy.bolt.enabled=true
dbms.ssl.policy.bolt.base_directory=certificates/bolt
dbms.ssl.policy.bolt.private_key=private.key
dbms.ssl.policy.bolt.public_certificate=public.crt
dbms.ssl.policy.bolt.client_auth=NONE
server.bolt.tls_level=REQUIRED

# Plugins
dbms.unmanaged_extension_classes=n10s.endpoint=/rdf
dbms.logs.debug.level=DEBUG
dbms.memory.heap.initial_size=2G
dbms.memory.heap.max_size=2G
```

apoc.conf:
```
# Enable importing and exporting of files
# apoc.export.file.enabled=true
# apoc.import.file.enabled=true
```

docker-compose.yaml:
```
version: '3.1'

services:
  graph:
    image: neo4j:5.11.0-community
    ports:
      - 20001:7687 # bolt+s
      # - 20011:7473 # https
      # - 50021:7474 # http
    volumes:
      - ./neo4j-data:/data
      - ./neo4j-logs:/logs
      - ./ssl:/ssl
      - ./conf:/conf
    environment:
      NEO4J_AUTH: neo4j/testtest
      NEO4J_dbms_memory_pagecache_size: "512m"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
```
