### ISSUE TITLE
`Docker compose` can't connect to database from back-end server running in docker compose

### ISSUE THREAD

**Issue by Parthiba-Hazra** [neo4j/neo4j#13381]
Cant connect to neo4j database from backend container running in same docker compose .. may be something wrong with my `DATABASE_URL` env. I also tried putting IP address to the url manually.

docker-compose.yaml - 
```
version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.rust
    environment:
      - DATABASE_URL=bolt://neo4j:neo12345@neo4j:7687
    ports:
      - "8080:8080"
    depends_on:
      - neo4j

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.react
    ports:
      - "8081:8081"
    depends_on:
      - backend

  neo4j:
    image: "neo4j:latest"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/neo12345"

```

create client function - 
```
async fn create_neo4j_client() -> Result<Graph, neo4rs::Error> {

    let x = "DATABASE_URL";
    let mut database_url = String::new();
    match env::var(x) {
        Ok(value) => {
            database_url = value;
            log::info!("The value of {} is: {}", x, database_url)
        } 
        Err(_) => {
            log::error!("{} is not set.", x)
        }
    }

    let config = ConfigBuilder::default()
        .uri(&database_url)
        .user(NEO4J_USER)
        .password(NEO4J_PASS)
        .db("neo4j")
        .fetch_size(500)
        .max_connections(10)
        .build()?;
    
    Graph::connect(config).await
}
```
OS - Ubuntu:23.10
