### ISSUE TITLE
Docker bind only provided network ip not all interfaces

### ISSUE THREAD

**Issue by jmcgroup3** [neo4j/neo4j#13410]
I can't get my neo4j docker-compose to only serve from 192.168.58.110

It binds on every interface 0.0.0.0 and I can access it via localhost:7474 which I don't want I want to isolate it.

````
// Both of these work but I only want the first one to be valid
const driver = neo4j.driver('neo4j://192.168.58.110', neo4j.auth.basic('neo4j', 'password'))
const driver = neo4j.driver('neo4j://localhost', neo4j.auth.basic('neo4j', 'password'))
````

I don't know if this is possible or I just have to accept that it binds localhost everything and nothing I can do.

````
services:
  graph:
    image: neo4j
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
      # - NEO4J_server_default_advertised__address=192.168.58.110
      - NEO4J_server_https_advertised__address=192.168.58.110
      - NEO4J_server_http_advertised__address=192.168.58.110
      - NEO4J_server_bolt_advertised__address=192.168.58.110
    networks:
      mynetwork:
        ipv4_address: 192.168.58.110

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.58.0/24
  ````
