### ISSUE TITLE
Failing Queries after upgrade to 5.21-enterprise 

### ISSUE THREAD

**Issue by boez-za** [neo4j/neo4j#13484]
## Bug report

We identified a bug in version 5.21 when processing queries. 
This query was tested in version 5.20, and was functional.
We noticed this issue this morning when queries started failing.

**Neo4j Version:** 5.21
**Operating System:** MacOS
**API:** Docker

### Requirements
- Docker
- Docker-compose
- A Web Browser 

### Steps to reproduce
1. Define the following docker-compose manifest  
```
version: '3.1'
name: 'neo4j-bug'
services:
  neo4j:
    image: neo4j:5.21.0-enterprise
    ports: 
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
```
2. Run the command `docker-compose up`
3. Wait for Ne4oj Services to Start
4. Navigate to localhost:7474 in a web browser 
5. Execute the following Cypher Query:
```
with *,'a test'  as this
//===================================================
call{ with this
    with *, '"' as DQe
    with *, '\'' as SQe
    with *, '\\' as BS1
    with *, '
' as LF   
    return  SQe, LF, BS1
}
return LF+BS1+LF+LF as x
``` 

### Expected behavior
The query should return the following result (export as json) without any errors:
```
[
  {
    "x": "
\

"
  }
]
```

### Actual behavior
The query errored with the following message:
```
Neo.ClientError.Statement.SyntaxError
Failed to parse string literal. The query must contain an even number of non-escaped quotes. (line 8, column 1 (offset: 180))
"' as LF"
```
