### ISSUE TITLE
ERROR Increase in network aborts detected

### ISSUE THREAD

**Issue by sanket-gandhi-melooha** [neo4j/neo4j#13640]
To help us understand your issue, please specify important details, primarily:

- Neo4j version: neo4j-5.26.1
- Installation method: helm chart on k8s cluster
- Deployed as neo4j cluster with size 3

getting same error as below for all pods 

2025-04-07 14:46:19.718+0000 INFO  Network abort rate has normalized
2025-04-07 14:47:58.538+0000 ERROR Increase in network aborts detected (more than 2 network related connection aborts over a period of 600000 ms) - This may indicate an issue with the network environment or an overload condition

Please let us to find what is wrong here

server-1-values.yaml
```
neo4j:
  name: "server"
  minimumClusterSize: 3
  resources:
    cpu: "0.5"
    memory: "2Gi"
  password: "xxxxxxxxxxx"
  edition: "enterprise"
  acceptLicenseAgreement: "yes"
services:
  neo4j:
    enabled: true
    ports:
      http:
        enabled: true 
      https:
        enabled: false
volumes:
  data:
    mode: "dynamic"
    dynamic:
      storageClassName: gp3
      requests:
        storage: 10Gi
```

server-2-values.yaml &  server-3-values.yaml
```
neo4j:
  name: "server"
  minimumClusterSize: 3
  resources:
    cpu: "0.5"
    memory: "2Gi"
  password: "xxxxxxxxxxx"
  edition: "enterprise"
  acceptLicenseAgreement: "yes"
services:
  neo4j:
    enabled: false
volumes:
  data:
    mode: "dynamic"
    dynamic:
      storageClassName: gp3
      requests:
        storage: 10Gi
```
