### ISSUE TITLE
Browser: result window expands on long property values

### ISSUE THREAD

**Issue by mtomala** [neo4j/neo4j#3774]
Neo4j 2.2.0-M02 - browser.

When nodes have properties with long values (text width is greater than result window width) the status block in result window expands horizontally with result window itself so nodes moves outside the screen. 
After that hovered node is no more hovered and status is changed back to "Displaying 25 nodes, 0 relationships" and it shrinks to original size. And after it shrinks and if mouse pointer is in the same place node gets hover again, and so on...

**Comment by oskarhane** [comment]
Thanks @mtomala!
I'll have a look at it.

**Comment by mtomala** [comment]
I'm not sure if it will fix it in all cases, but for me addind those styles helps:
```css
.inspector-footer-row > ul {
   overflow: auto;
}
.view-result-plan, .view-result-graph .graph-holder {
   table-layout: fixed;
}
```
